name: 'LeanIX k8s deploy'
description: 'Perform deployment to kubernetes cluster'
inputs:
  namespace:
    description: 'kubernetes namespace'
    required: true
  environment:
    description:  'The cluster environment, e.g. test or prod'
    required: true
    default: 'test'
  template_directory:
    description: 'Directory containing the kubernetes deployment files'
    required: true
    default: 'k8s-deployment'
  vault_secret_keys:
    description: 'Vault secret keys to provide as k8s secrets'
    required: false
  dry_run:
    description: 'Set to true for dry run mode: Only validate and render the templates, not actually deploying to any cluster'
    required: false
runs:
  using: 'docker'
  image: 'docker://leanix/k8s-deploy:latest'